### ISSUE TITLE
Error: Call to undefined function entity_access

### ISSUE THREAD

**Issue by deaddred** [backdrop-contrib/group#6]
BO 1.12.6
Group - latest build

After adding a group type and going to admin/group/overview I get a white screen and this error is reported.

Error: Call to undefined function entity_access() in _group_add_access() (line 66 of /home/xlouxheh/public_html/modules/group-1.x-1.x/group.router.inc).

**Comment by herbdool** [comment]
`entity_access` is now in core so I think we can close this.
